# Generated by Django 3.1.3 on 2021-04-21 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jcc',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jcc',
            name='endidad_lugar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitio.entidad'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='from_jcc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitio.jcc'),
        ),
    ]
