# Generated by Django 3.1.3 on 2021-04-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_sitio_web_color_text_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio_web',
            name='color_contenido',
            field=models.CharField(default='rgb(9, 79, 102)', max_length=20, verbose_name='Color contenido'),
        ),
    ]
