# Generated by Django 3.1.3 on 2021-04-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_sitio_web_color_fondo_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio_web',
            name='color_activo_menu',
            field=models.CharField(default='#007bff', max_length=20, verbose_name='Color activo menu'),
        ),
        migrations.AlterField(
            model_name='sitio_web',
            name='color_contenido',
            field=models.CharField(default='#fffff', max_length=20, verbose_name='Color contenido'),
        ),
        migrations.AlterField(
            model_name='sitio_web',
            name='color_fondo_inicio',
            field=models.CharField(default='#26bdef', max_length=20, verbose_name='Color Fondo Inicio'),
        ),
        migrations.AlterField(
            model_name='sitio_web',
            name='color_footer',
            field=models.CharField(default='#e8e8ea', max_length=20, verbose_name='Color footer'),
        ),
        migrations.AlterField(
            model_name='sitio_web',
            name='color_header',
            field=models.CharField(default='#26bdef', max_length=20, verbose_name='Color header'),
        ),
        migrations.AlterField(
            model_name='sitio_web',
            name='color_sider',
            field=models.CharField(default='#0087c3', max_length=20, verbose_name='Color sider'),
        ),
    ]
