# Generated by Django 3.1.3 on 2021-04-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_entidad'),
        ('sitio', '0006_auto_20210427_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jcc',
            name='director',
        ),
        migrations.RemoveField(
            model_name='jcc',
            name='endidad_lugar',
        ),
        migrations.DeleteModel(
            name='Entidad',
        ),
        migrations.DeleteModel(
            name='Jcc',
        ),
    ]
