# Generated by Django 3.1.3 on 2021-09-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomodulo',
            name='icono',
            field=models.CharField(max_length=20, verbose_name='Icono'),
        ),
    ]
