# Generated by Django 3.1.3 on 2021-09-11 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preMatricula', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField(unique=True, verbose_name='Carne Identidad')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=150, verbose_name='Apellido Paterno')),
                ('apellido2', models.CharField(max_length=150, verbose_name='Apellido Materno')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('correo', models.CharField(max_length=100, unique=True, verbose_name='Correo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatar', verbose_name='Avatar')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='preMatricula.municipio', verbose_name='Municipio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
