# Generated by Django 3.1.3 on 2021-09-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ci',
            field=models.IntegerField(max_length=11, unique=True, verbose_name='Carne Identidad'),
        ),
    ]
