# Generated by Django 3.1.3 on 2021-09-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210911_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='users/avatar', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ci',
            field=models.IntegerField(unique=True, verbose_name='Carne Identidad'),
        ),
    ]
