# Generated by Django 3.1.3 on 2021-09-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_perfil_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('ES', 'Estudiante'), ('PR', 'Profesor'), ('GE', 'Gestor'), ('IN', 'Instructor'), ('AD', 'Admin')], default='ES', max_length=2),
        ),
    ]
