# Generated by Django 3.1.3 on 2021-10-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210921_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='gestor',
            field=models.BooleanField(default=False),
        ),
    ]
