# Generated by Django 3.1.3 on 2021-04-28 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Entidad')),
                ('telefono', models.CharField(max_length=8, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='JCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_jcp', models.CharField(max_length=10, unique=True, verbose_name='Codigo JCP')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.entidad', verbose_name='Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_region', models.CharField(max_length=10, verbose_name='Código Región')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Región')),
                ('jcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.jcp', verbose_name='Joven Club Provincial')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Municipio')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='JCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_jcm', models.CharField(max_length=10, verbose_name='Código Joven Club Municipal')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.entidad', verbose_name='Entidad')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.region', verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='JCB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_jcb', models.CharField(max_length=10, verbose_name='Código Joven Club')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.entidad', verbose_name='Entidad')),
                ('jcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.jcm', verbose_name='Joven Club Municipal')),
            ],
        ),
        migrations.AddField(
            model_name='entidad',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preMatricula.municipio', verbose_name='Municipio'),
        ),
    ]
