# Generated by Django 3.1.3 on 2021-09-17 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preMatricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreMatriculaMaestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.maestro', verbose_name='Maestro')),
                ('preMatricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.prematricula', verbose_name='Pre-Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.estudiante', verbose_name='Estudiante')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.gestor', verbose_name='Gestor')),
            ],
        ),
        migrations.CreateModel(
            name='GestorEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.estudiante', verbose_name='Estudiante')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.gestor', verbose_name='Gestor')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto del comentario')),
                ('fecha_comentario', models.DateField(auto_now=True, verbose_name='Fecha Creado')),
                ('preMatricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.prematricula', verbose_name='Pre matricula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
