# Generated by Django 3.1.3 on 2021-09-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreMatriculaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(verbose_name='El Estudiante ha sido chequeado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.estudiante', verbose_name='Estudiante')),
                ('preMatricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.prematricula', verbose_name='Pre-Matricula')),
            ],
        ),
    ]
