# Generated by Django 3.1.3 on 2021-09-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('preMatricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('usuario_siscae', models.CharField(max_length=50, null=True, verbose_name='Usuario del siscae')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='Usuario')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='preMatricula.cargo', verbose_name='Cargo')),
                ('jcb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='preMatricula.jcb', verbose_name='Joven Club')),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='preMatricula.instructor', verbose_name='Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.estudiante', verbose_name='Estudiante')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.instructor', verbose_name='Gestor')),
            ],
        ),
        migrations.CreateModel(
            name='PreMatriculaMaestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preMatricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.prematricula', verbose_name='Pre-Matricula')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.maestro', verbose_name='Maestro')),
            ],
        ),
    ]
