# Generated by Django 3.1.3 on 2021-09-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0002_comentario_gestorestudiante_instructorestudiante_prematriculamaestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, default='curso_default.png', null=True, upload_to='curso/foto', verbose_name='Foto'),
        ),
    ]
