# Generated by Django 3.1.3 on 2021-04-29 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0003_auto_20210428_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteCursoSiscae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoSiscae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.cursosiscae', verbose_name='Curso Siscae')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.estudiante', verbose_name='Estudiante')),
            ],
        ),
    ]
