# Generated by Django 3.1.3 on 2021-09-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0003_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
