# Generated by Django 3.1.3 on 2021-09-20 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0005_auto_20210919_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='respuestaA',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='preMatricula.comentario', verbose_name='Respuesta a'),
        ),
    ]
