# Generated by Django 3.1.3 on 2021-05-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0006_auto_20210502_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Provincia'),
        ),
    ]
