# Generated by Django 3.1.3 on 2021-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0006_auto_20210920_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Creado'),
        ),
    ]
