# Generated by Django 3.1.3 on 2021-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0007_auto_20210920_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='leido',
            field=models.BooleanField(default=True),
        ),
    ]
