# Generated by Django 3.1.3 on 2021-09-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0008_comentario_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
