# Generated by Django 3.1.3 on 2021-05-15 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preMatricula', '0008_auto_20210515_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jcb',
            name='entidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.entidad', verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='jcm',
            name='entidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.entidad', verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='jcp',
            name='entidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.entidad', verbose_name='Entidad'),
        ),
    ]
