# Generated by Django 3.1.3 on 2021-08-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0009_auto_20210515_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='estadomatricula',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Estado Matricula'),
        ),
    ]
