# Generated by Django 3.1.3 on 2021-09-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0010_auto_20210831_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jcm',
            name='codigo_jcm',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código Joven Club Municipal'),
        ),
        migrations.AlterField(
            model_name='region',
            name='codigo_region',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código Región'),
        ),
    ]
