# Generated by Django 3.1.3 on 2021-09-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0010_prematricula_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prematricula',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='prematricula',
            name='qr',
        ),
    ]
