# Generated by Django 3.1.3 on 2021-09-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0011_auto_20210923_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='prematricula',
            name='jcb',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='preMatricula.jcb', verbose_name='Joven Club'),
        ),
        migrations.AlterField(
            model_name='prematriculaestudiante',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='El Estudiante ha sido chequeado'),
        ),
    ]
