# Generated by Django 3.1.3 on 2021-09-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0011_auto_20210905_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jcb',
            name='codigo_jcb',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código Joven Club'),
        ),
    ]
