# Generated by Django 3.1.3 on 2021-09-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0012_auto_20210924_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='prematricula',
            name='fecha_creado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
