# Generated by Django 3.1.3 on 2021-10-15 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preMatricula', '0013_prematricula_fecha_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='jcm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preMatricula.jcm', verbose_name='Joven Club Municipal'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
