# Generated by Django 3.1.3 on 2021-10-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0014_auto_20211015_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='corto',
        ),
        migrations.RemoveField(
            model_name='prematricula',
            name='tipo_grupo',
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.CharField(choices=[('24', '24 horas'), ('36', '36 horas'), ('64', '64 horas')], default='24', max_length=2, verbose_name='Duración en Horas'),
        ),
        migrations.DeleteModel(
            name='TipoGrupo',
        ),
    ]
