# Generated by Django 3.1.3 on 2021-10-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0015_auto_20211022_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prematricula',
            name='estado',
            field=models.CharField(choices=[('AB', 'abierto'), ('CE', 'cerrado'), ('PR', 'proceso')], default='AB', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='prematricula',
            name='modalidad',
            field=models.CharField(choices=[('PR', 'presencial'), ('SE', 'semi-presencial')], default='PR', max_length=2, verbose_name='Modalidad'),
        ),
        migrations.DeleteModel(
            name='EstadoMatricula',
        ),
        migrations.DeleteModel(
            name='Modalidad',
        ),
    ]
