# Generated by Django 3.1.3 on 2021-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preMatricula', '0016_auto_20211024_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='prematriculaestudiante',
            name='fecha_creado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prematricula',
            name='capacidad',
            field=models.IntegerField(verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='prematricula',
            name='frecuencia',
            field=models.IntegerField(verbose_name='Frecuencia'),
        ),
    ]
