# Generated by Django 3.1.3 on 2021-04-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ci',
        ),
    ]
