# Generated by Django 3.1.3 on 2021-04-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='entidad',
        ),
    ]
