# Generated by Django 3.1.3 on 2021-04-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_entidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='domina',
        ),
        migrations.DeleteModel(
            name='Etiqueta_Domina',
        ),
    ]
