# Generated by Django 3.1.3 on 2021-04-28 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.estado', verbose_name='Estado del Usuario'),
        ),
    ]
