# Generated by Django 3.1.3 on 2021-04-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_perfil_ci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='ci',
        ),
    ]
