# Generated by Django 3.1.3 on 2021-05-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_perfil_ci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
