# Generated by Django 3.1.3 on 2021-05-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210515_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ci',
            field=models.IntegerField(default=12345678987, max_length=11, verbose_name='Carne Identidad'),
        ),
    ]
