# Generated by Django 3.1.3 on 2021-05-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_perfil_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ci',
            field=models.IntegerField(unique=True, verbose_name='Carne Identidad'),
        ),
    ]
